-- H2 测试数据库表结构（兼容 PostgreSQL 模式）
-- 该文件用于集成测试的 schema 初始化。

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    owner_name VARCHAR(255),
    owner_avatar_id VARCHAR(64),
    owner_profile_version BIGINT DEFAULT 0,
    title VARCHAR(200) NOT NULL,
    excerpt TEXT,
    cover_image_id VARCHAR(64),
    status INT NOT NULL DEFAULT 0,
    write_state VARCHAR(32) NOT NULL DEFAULT 'NONE',
    incomplete_reason TEXT,
    topic_id BIGINT,
    published_at TIMESTAMP,
    scheduled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    
    -- Stats columns (embedded PostStats)
    view_count INT DEFAULT 0,
    like_count INT DEFAULT 0,
    favorite_count INT DEFAULT 0,
    comment_count INT DEFAULT 0,
    share_count INT DEFAULT 0,
    
    -- Data quality constraints
    CONSTRAINT ck_posts_title_not_blank CHECK (LENGTH(TRIM(title)) > 0),
    CONSTRAINT ck_posts_status_valid CHECK (status IN (0, 1, 2, 3))
);

-- Indexes for posts
CREATE INDEX IF NOT EXISTS idx_posts_owner_id ON posts(owner_id);
CREATE INDEX IF NOT EXISTS idx_posts_status ON posts(status);
CREATE INDEX IF NOT EXISTS idx_posts_published_at ON posts(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_topic_id ON posts(topic_id);
CREATE INDEX IF NOT EXISTS idx_posts_owner_profile_version ON posts(owner_id, owner_profile_version);
CREATE INDEX IF NOT EXISTS idx_posts_is_archived ON posts(is_archived);

-- Comments for posts
COMMENT ON TABLE posts IS '文章表';
COMMENT ON COLUMN posts.id IS '文章ID（雪花算法）';
COMMENT ON COLUMN posts.owner_id IS '作者ID';
COMMENT ON COLUMN posts.owner_name IS '作者昵称快照（冗余字段）';
COMMENT ON COLUMN posts.owner_avatar_id IS '作者头像文件ID快照';
COMMENT ON COLUMN posts.owner_profile_version IS '作者资料版本号（用于防止消息乱序）';
COMMENT ON COLUMN posts.title IS '文章标题';
COMMENT ON COLUMN posts.status IS '文章状态：0=DRAFT, 1=PUBLISHED, 2=SCHEDULED, 3=DELETED';
COMMENT ON COLUMN posts.write_state IS '写入状态（用于一致性修复与清理）';
COMMENT ON COLUMN posts.version IS '乐观锁版本号';

-- Post Stats table schema for H2 test database
CREATE TABLE IF NOT EXISTS post_stats (
    post_id BIGINT PRIMARY KEY,
    like_count INT DEFAULT 0,
    comment_count INT DEFAULT 0,
    favorite_count INT DEFAULT 0,
    share_count INT DEFAULT 0,
    view_count BIGINT DEFAULT 0,
    last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for post_stats
CREATE INDEX IF NOT EXISTS idx_post_stats_like_count ON post_stats(like_count DESC);
CREATE INDEX IF NOT EXISTS idx_post_stats_view_count ON post_stats(view_count DESC);

-- Comments for post_stats
COMMENT ON TABLE post_stats IS '文章统计表';
COMMENT ON COLUMN post_stats.post_id IS '文章ID';
COMMENT ON COLUMN post_stats.like_count IS '点赞数';
COMMENT ON COLUMN post_stats.comment_count IS '评论数';
COMMENT ON COLUMN post_stats.favorite_count IS '收藏数';
COMMENT ON COLUMN post_stats.share_count IS '分享数';
COMMENT ON COLUMN post_stats.view_count IS '浏览数';

-- Outbox 表（测试环境最小兼容）
CREATE TABLE IF NOT EXISTS outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(32) NOT NULL UNIQUE,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    aggregate_version BIGINT NOT NULL,
    schema_version INT NOT NULL DEFAULT 1,
    payload TEXT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_at TIMESTAMP,
    claimed_by VARCHAR(128),
    dispatched_at TIMESTAMP,
    retry_count INT NOT NULL DEFAULT 0,
    last_error TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
);

CREATE INDEX IF NOT EXISTS idx_outbox_event_status_created ON outbox_event(status, created_at);
CREATE INDEX IF NOT EXISTS idx_outbox_event_status_attempt ON outbox_event(status, next_attempt_at, created_at);
CREATE INDEX IF NOT EXISTS idx_outbox_event_event_id ON outbox_event(event_id);
CREATE INDEX IF NOT EXISTS idx_outbox_event_aggregate ON outbox_event(aggregate_id, aggregate_version);
CREATE INDEX IF NOT EXISTS idx_outbox_event_aggregate_order ON outbox_event(aggregate_id, aggregate_version, created_at, id);

CREATE TABLE IF NOT EXISTS domain_event_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(32) NOT NULL UNIQUE,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id BIGINT,
    aggregate_version BIGINT,
    schema_version INT NOT NULL DEFAULT 1,
    payload TEXT NOT NULL,
    priority INT NOT NULL DEFAULT 100,
    occurred_at TIMESTAMP NOT NULL,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_at TIMESTAMP,
    claimed_by VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispatched_at TIMESTAMP,
    retry_count INT NOT NULL DEFAULT 0,
    last_error TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
);

CREATE INDEX IF NOT EXISTS idx_domain_event_task_status_attempt
    ON domain_event_task(status, next_attempt_at, priority, created_at);
CREATE INDEX IF NOT EXISTS idx_domain_event_task_aggregate_order
    ON domain_event_task(aggregate_id, aggregate_version, created_at, id);

-- Outbox 手动重试审计（R14，测试环境最小兼容）
CREATE TABLE IF NOT EXISTS outbox_retry_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(32) NOT NULL,
    operator_id BIGINT NOT NULL,
    reason TEXT,
    retried_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbox_retry_audit_event_id_retried_at
    ON outbox_retry_audit(event_id, retried_at DESC);

-- 定时发布事件表（R1，测试环境最小兼容）
CREATE TABLE IF NOT EXISTS scheduled_publish_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(32) NOT NULL UNIQUE,
    trigger_event_id VARCHAR(32),
    post_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    reschedule_retry_count INT NOT NULL DEFAULT 0,
    publish_retry_count INT NOT NULL DEFAULT 0,
    claimed_at TIMESTAMP,
    claimed_by VARCHAR(128),
    last_error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_spe_status_attempt ON scheduled_publish_event(status, next_attempt_at, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_spe_trigger_event_id ON scheduled_publish_event(trigger_event_id);
CREATE INDEX IF NOT EXISTS idx_spe_post_id ON scheduled_publish_event(post_id);

-- Tags table schema for H2 test database
-- This schema is compatible with H2's PostgreSQL mode

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    slug VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Data quality constraints
    CONSTRAINT ck_tags_name_not_blank CHECK (LENGTH(TRIM(name)) > 0),
    CONSTRAINT ck_tags_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_slug ON tags(slug);
CREATE INDEX IF NOT EXISTS idx_tags_name ON tags(name);
CREATE INDEX IF NOT EXISTS idx_tags_created_at ON tags(created_at DESC);

-- Comments
COMMENT ON TABLE tags IS '标签表';
COMMENT ON COLUMN tags.id IS '标签ID（雪花算法）';
COMMENT ON COLUMN tags.name IS '标签展示名称';
COMMENT ON COLUMN tags.slug IS 'URL友好标识（唯一）';
COMMENT ON COLUMN tags.description IS '标签描述';

-- Post-Tags association table schema for H2 test database
CREATE TABLE IF NOT EXISTS post_tags (
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (post_id, tag_id)
);

-- Indexes for post_tags
CREATE INDEX IF NOT EXISTS idx_post_tags_tag_post ON post_tags(tag_id, post_id);
CREATE INDEX IF NOT EXISTS idx_post_tags_post_tag ON post_tags(post_id, tag_id);
CREATE INDEX IF NOT EXISTS idx_post_tags_created_at ON post_tags(created_at DESC);

-- Comments for post_tags
COMMENT ON TABLE post_tags IS '文章标签关联表';
COMMENT ON COLUMN post_tags.post_id IS '文章ID';
COMMENT ON COLUMN post_tags.tag_id IS '标签ID';

-- 点赞表（R2）
CREATE TABLE IF NOT EXISTS post_likes (
    id BIGINT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_post_likes_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_post_likes_post_id ON post_likes(post_id);
CREATE INDEX IF NOT EXISTS idx_post_likes_user_id_created_at ON post_likes(user_id, created_at DESC);

-- 收藏表（R3）
CREATE TABLE IF NOT EXISTS post_favorites (
    id BIGINT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_post_favorites_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_post_favorites_post_id ON post_favorites(post_id);
CREATE INDEX IF NOT EXISTS idx_post_favorites_user_id_created_at ON post_favorites(user_id, created_at DESC);

-- 标签统计表
CREATE TABLE IF NOT EXISTS tag_stats (
    tag_id BIGINT PRIMARY KEY,
    post_count INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 已消费事件表（幂等）
CREATE TABLE IF NOT EXISTS consumed_events (
    event_id VARCHAR(64) PRIMARY KEY,
    event_type VARCHAR(255) NOT NULL,
    consumer_name VARCHAR(255) NOT NULL,
    consumed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_consumed_events_consumed_at ON consumed_events(consumed_at);
