ALTER TABLE IF EXISTS comments
    ADD COLUMN IF NOT EXISTS image_ids TEXT[];

ALTER TABLE IF EXISTS comments
    ADD COLUMN IF NOT EXISTS voice_id VARCHAR(36);

ALTER TABLE IF EXISTS comments
    ADD COLUMN IF NOT EXISTS voice_duration INTEGER;
